var DataSet = {
"chemicals":
{
100414:{
    "order_by": "50",
    "chemical_nm": "Ethylbenzene",
    "chemical_label_tx": "Ethylbenzene<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "100414",
    "fc_water_org": "68",
    "fc_org": "130",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.022",
    "bio_acc_tl2": "100",
    "bio_acc_tl3": "140",
    "bio_acc_tl4": "160",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E90*$D90*$C$3*1000)/($C$4+$C$5*$F90+$C$6*$G90+$C$7*$H90)",
    "equation_awqc_org": "=($E90*$D90*$C$3*1000)/($C$5*$F90+$C$6*$G90+$C$7*$H90)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
1024573:{
    "order_by": "54",
    "chemical_nm": "Heptachlor Epoxide",
    "chemical_label_tx": "Heptachlor Epoxide<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "1024573",
    "fc_water_org": "0.000032",
    "fc_org": "0.000032",
    "cancer_slope": "5.5",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "4000",
    "bio_acc_tl3": "28000",
    "bio_acc_tl4": "35000",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C95)*$C$3*1000/($C$4+$C$5*$F95+$C$6*$G95+$C$7*$H95)",
    "equation_awqc_org": "=(($C$9/$C95)*$C$3*1000)/($C$5*$F95+$C$6*$G95+$C$7*$H95)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
1031078:{
    "order_by": "47",
    "chemical_nm": "Endosulfan Sulfate",
    "chemical_label_tx": "Endosulfan Sulfate",
    "super_script_tx": "",
    "cas_number": "1031078",
    "fc_water_org": "20",
    "fc_org": "40",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.006",
    "bio_acc_tl2": "88",
    "bio_acc_tl3": "120",
    "bio_acc_tl4": "140",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E87*$D87*$C$3*1000)/($C$4+$C$5*$F87+$C$6*$G87+$C$7*$H87)",
    "equation_awqc_org": "=($E87*$D87*$C$3*1000)/($C$5*$F87+$C$6*$G87+$C$7*$H87)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
105679:{
    "order_by": "113",
    "chemical_nm": "2,4-Dimethylphenol",
    "chemical_label_tx": "2,4-Dimethylphenol<sup>c</sup>",
    "super_script_tx": "c",
    "cas_number": "105679",
    "fc_water_org": "100",
    "fc_org": "3,000",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.02",
    "bio_acc_tl2": "4.8",
    "bio_acc_tl3": "6.2",
    "bio_acc_tl4": "7",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E38*$D38*$C$3*1000)/($C$4+$C$5*$F38+$C$6*$G38+$C$7*$H38)",
    "equation_awqc_org": "=($E38*$D38*$C$3*1000)/($C$5*$F38+$C$6*$G38+$C$7*$H38)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
106467:{
    "order_by": "108",
    "chemical_nm": "1,4-Dichlorobenzene",
    "chemical_label_tx": "1,4-Dichlorobenzene<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "106467",
    "fc_water_org": "300",
    "fc_org": "900",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.07",
    "bio_acc_tl2": "28",
    "bio_acc_tl3": "66",
    "bio_acc_tl4": "84",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E34*$D34*$C$3*1000)/($C$4+$C$5*$F34+$C$6*$G34+$C$7*$H34)",
    "equation_awqc_org": "=($E34*$D34*$C$3*1000)/($C$5*$F34+$C$6*$G34+$C$7*$H34)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
107028:{
    "order_by": "2",
    "chemical_nm": "Acrolein",
    "chemical_label_tx": "Acrolein",
    "super_script_tx": "",
    "cas_number": "107028",
    "fc_water_org": "3",
    "fc_org": "400",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.0005",
    "bio_acc_tl2": "1",
    "bio_acc_tl3": "1",
    "bio_acc_tl4": "1.0",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E50*$D50*$C$3*1000)/($C$4+$C$5*$F50+$C$6*$G50+$C$7*$H50)",
    "equation_awqc_org": "=($E50*$D50*$C$3*1000)/($C$5*$F50+$C$6*$G50+$C$7*$H50)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
107062:{
    "order_by": "102",
    "chemical_nm": "1,2-Dichloroethane",
    "chemical_label_tx": "1,2-Dichloroethane<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "107062",
    "fc_water_org": "9.9",
    "fc_org": "650",
    "cancer_slope": "0.0033",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "1.6",
    "bio_acc_tl3": "1.8",
    "bio_acc_tl4": "1.9",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C28)*$C$3*1000/($C$4+$C$5*$F28+$C$6*$G28+$C$7*$H28)",
    "equation_awqc_org": "=(($C$9/$C28)*$C$3*1000)/($C$5*$F28+$C$6*$G28+$C$7*$H28)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
107131:{
    "order_by": "3",
    "chemical_nm": "Acrylonitrile",
    "chemical_label_tx": "Acrylonitrile<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "107131",
    "fc_water_org": "0.061",
    "fc_org": "7",
    "cancer_slope": "0.54",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "1",
    "bio_acc_tl3": "1",
    "bio_acc_tl4": "1.0",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C51)*$C$3*1000/($C$4+$C$5*$F51+$C$6*$G51+$C$7*$H51)",
    "equation_awqc_org": "=(($C$9/$C51)*$C$3*1000)/($C$5*$F51+$C$6*$G51+$C$7*$H51)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
108601:{
    "order_by": "21",
    "chemical_nm": "*Bis(2-Chloro-1-Methylethyl) Ether ",
    "chemical_label_tx": "*Bis(2-Chloro-1-Methylethyl) Ether ",
    "super_script_tx": "",
    "cas_number": "108601",
    "fc_water_org": "200",
    "fc_org": "4,000",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.04",
    "bio_acc_tl2": "6.7",
    "bio_acc_tl3": "8.8",
    "bio_acc_tl4": "10",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E65*$D65*$C$3*1000)/($C$4+$C$5*$F65+$C$6*$G65+$C$7*$H65)",
    "equation_awqc_org": "=($E65*$D65*$C$3*1000)/($C$5*$F65+$C$6*$G65+$C$7*$H65)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
108883:{
    "order_by": "90",
    "chemical_nm": "Toluene",
    "chemical_label_tx": "Toluene<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "108883",
    "fc_water_org": "57",
    "fc_org": "520",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.0097",
    "bio_acc_tl2": "11",
    "bio_acc_tl3": "15",
    "bio_acc_tl4": "17",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E121*$D121*$C$3*1000)/($C$4+$C$5*$F121+$C$6*$G121+$C$7*$H121)",
    "equation_awqc_org": "=($E121*$D121*$C$3*1000)/($C$5*$F121+$C$6*$G121+$C$7*$H121)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
108907:{
    "order_by": "30",
    "chemical_nm": "Chlorobenzene",
    "chemical_label_tx": "Chlorobenzene<sup>a,c</sup>",
    "super_script_tx": "a,c",
    "cas_number": "108907",
    "fc_water_org": "100",
    "fc_org": "800",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.02",
    "bio_acc_tl2": "14",
    "bio_acc_tl3": "19",
    "bio_acc_tl4": "22",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E73*$D73*$C$3*1000)/($C$4+$C$5*$F73+$C$6*$G73+$C$7*$H73)",
    "equation_awqc_org": "=($E73*$D73*$C$3*1000)/($C$5*$F73+$C$6*$G73+$C$7*$H73)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
108952:{
    "order_by": "83",
    "chemical_nm": "Phenol",
    "chemical_label_tx": "Phenol<sup>c</sup>",
    "super_script_tx": "c",
    "cas_number": "108952",
    "fc_water_org": "4,000",
    "fc_org": "300,000",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.6",
    "bio_acc_tl2": "1.5",
    "bio_acc_tl3": "1.7",
    "bio_acc_tl4": "1.9",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E116*$D116*$C$3*1000)/($C$4+$C$5*$F116+$C$6*$G116+$C$7*$H116)",
    "equation_awqc_org": "=($E116*$D116*$C$3*1000)/($C$5*$F116+$C$6*$G116+$C$7*$H116)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
111444:{
    "order_by": "22",
    "chemical_nm": "Bis(2-Chloroethyl) Ether",
    "chemical_label_tx": "Bis(2-Chloroethyl) Ether<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "111444",
    "fc_water_org": "0.03",
    "fc_org": "2.2",
    "cancer_slope": "1.1",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "1.4",
    "bio_acc_tl3": "1.6",
    "bio_acc_tl4": "1.7",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C66)*$C$3*1000/($C$4+$C$5*$F66+$C$6*$G66+$C$7*$H66)",
    "equation_awqc_org": "=(($C$9/$C66)*$C$3*1000)/($C$5*$F66+$C$6*$G66+$C$7*$H66)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
117817:{
    "order_by": "23",
    "chemical_nm": "Bis(2-Ethylhexyl) Phthalate",
    "chemical_label_tx": "Bis(2-Ethylhexyl) Phthalate<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "117817",
    "fc_water_org": "0.32",
    "fc_org": "0.37",
    "cancer_slope": "0.014",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "710",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C67)*$C$3*1000)/($C$4+($C$8*$J67))",
    "equation_awqc_org": "=(($C$9/$C67)*$C$3*1000)/($C$8*$J67)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
118741:{
    "order_by": "56",
    "chemical_nm": "Hexachlorobenzene",
    "chemical_label_tx": "Hexachlorobenzene<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "118741",
    "fc_water_org": "0.000079",
    "fc_org": "0.000079",
    "cancer_slope": "1.02",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "18000",
    "bio_acc_tl3": "46000",
    "bio_acc_tl4": "90000",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C96)*$C$3*1000/($C$4+$C$5*$F96+$C$6*$G96+$C$7*$H96)",
    "equation_awqc_org": "=(($C$9/$C96)*$C$3*1000)/($C$5*$F96+$C$6*$G96+$C$7*$H96)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
120127:{
    "order_by": "7",
    "chemical_nm": "Anthracene",
    "chemical_label_tx": "Anthracene",
    "super_script_tx": "",
    "cas_number": "120127",
    "fc_water_org": "300",
    "fc_org": "400",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.3",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "610",
    "sig_figs_nu": "1",
    "methodology_type": "BAC",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E55*$D55*$C$3*1000)/($C$4+($C$8*$J55))",
    "equation_awqc_org": "=($D55*$E55*$C$3*1000)/($C$8*$J55)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "(rel_source_cont*ref_dose*BW*1000)/(FCR_T*bio_con)"
},
120821:{
    "order_by": "100",
    "chemical_nm": "1,2,4-Trichlorobenzene",
    "chemical_label_tx": "1,2,4-Trichlorobenzene<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "120821",
    "fc_water_org": "0.071",
    "fc_org": "0.076",
    "cancer_slope": "0.029",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "2800",
    "bio_acc_tl3": "1500",
    "bio_acc_tl4": "430",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C25)*$C$3*1000/($C$4+$C$5*$F25+$C$6*$G25+$C$7*$H25)",
    "equation_awqc_org": "=(($C$9/$C25)*$C$3*1000)/($C$5*$F25+$C$6*$G25+$C$7*$H25)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
120832:{
    "order_by": "112",
    "chemical_nm": "2,4-Dichlorophenol",
    "chemical_label_tx": "2,4-Dichlorophenol<sup>c</sup>",
    "super_script_tx": "c",
    "cas_number": "120832",
    "fc_water_org": "10",
    "fc_org": "60",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.003",
    "bio_acc_tl2": "31",
    "bio_acc_tl3": "42",
    "bio_acc_tl4": "48",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E37*$D37*$C$3*1000)/($C$4+$C$5*$F37+$C$6*$G37+$C$7*$H37)",
    "equation_awqc_org": "=($E37*$D37*$C$3*1000)/($C$5*$F37+$C$6*$G37+$C$7*$H37)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
121142:{
    "order_by": "115",
    "chemical_nm": "2,4-Dinitrotoluene",
    "chemical_label_tx": "2,4-Dinitrotoluene<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "121142",
    "fc_water_org": "0.049",
    "fc_org": "1.7",
    "cancer_slope": "0.667",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "2.8",
    "bio_acc_tl3": "3.5",
    "bio_acc_tl4": "3.9",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C40)*$C$3*1000/($C$4+$C$5*$F40+$C$6*$G40+$C$7*$H40)",
    "equation_awqc_org": "=(($C$9/$C40)*$C$3*1000)/($C$5*$F40+$C$6*$G40+$C$7*$H40)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
122667:{
    "order_by": "104",
    "chemical_nm": "1,2-Diphenylhydrazine",
    "chemical_label_tx": "1,2-Diphenylhydrazine<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "122667",
    "fc_water_org": "0.03",
    "fc_org": "0.2",
    "cancer_slope": "0.8",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "18",
    "bio_acc_tl3": "24",
    "bio_acc_tl4": "27",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C30)*$C$3*1000/($C$4+$C$5*$F30+$C$6*$G30+$C$7*$H30)",
    "equation_awqc_org": "=(($C$9/$C30)*$C$3*1000)/($C$5*$F30+$C$6*$G30+$C$7*$H30)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
124481:{
    "order_by": "31",
    "chemical_nm": "Chlorodibromomethane",
    "chemical_label_tx": "Chlorodibromomethane<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "124481",
    "fc_water_org": "0.8",
    "fc_org": "21",
    "cancer_slope": "0.04",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "3.7",
    "bio_acc_tl3": "4.8",
    "bio_acc_tl4": "5.3",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C74)*$C$3*1000/($C$4+$C$5*$F74+$C$6*$G74+$C$7*$H74)",
    "equation_awqc_org": "=(($C$9/$C74)*$C$3*1000)/($C$5*$F74+$C$6*$G74+$C$7*$H74)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
127184:{
    "order_by": "88",
    "chemical_nm": "Tetrachloroethylene",
    "chemical_label_tx": "Tetrachloroethylene<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "127184",
    "fc_water_org": "10",
    "fc_org": "29",
    "cancer_slope": "0.0021",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "49",
    "bio_acc_tl3": "66",
    "bio_acc_tl4": "76",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C120)*$C$3*1000/($C$4+$C$5*$F120+$C$6*$G120+$C$7*$H120)",
    "equation_awqc_org": "=(($C$9/$C120)*$C$3*1000)/($C$5*$F120+$C$6*$G120+$C$7*$H120)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
129000:{
    "order_by": "85",
    "chemical_nm": "Pyrene",
    "chemical_label_tx": "Pyrene",
    "super_script_tx": "h",
    "cas_number": "129000",
    "fc_water_org": "20",
    "fc_org": "30",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.03",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "860",
    "sig_figs_nu": "1",
    "methodology_type": "BAC",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E118*$D118*$C$3*1000)/($C$4+($C$8*$J118))",
    "equation_awqc_org": "=($D118*$E118*$C$3*1000)/($C$8*$J118)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "(rel_source_cont*ref_dose*BW*1000)/(FCR_T*bio_con)"
},
131113:{
    "order_by": "44",
    "chemical_nm": "Dimethyl Phthalate",
    "chemical_label_tx": "Dimethyl Phthalate",
    "super_script_tx": "",
    "cas_number": "131113",
    "fc_water_org": "2,000",
    "fc_org": "2,000",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "10",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "4,000",
    "sig_figs_nu": "1",
    "methodology_type": "BAC",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E84*$D84*$C$3*1000)/($C$4+($C$8*$J84))",
    "equation_awqc_org": "=($D84*$E84*$C$3*1000)/($C$8*$J84)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "(rel_source_cont*ref_dose*BW*1000)/(FCR_T*bio_con)"
},
1336363:{
    "order_by": "84",
    "chemical_nm": "Polychlorinated Biphenyls (PCBs)",
    "chemical_label_tx": "Polychlorinated Biphenyls (PCBs)<sup>a,b,h</sup>",
    "super_script_tx": "a,b",
    "cas_number": "1336363",
    "fc_water_org": "0.000064",
    "fc_org": "0.000064",
    "cancer_slope": "2",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "31200",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C117)*$C$3*1000)/($C$4+($C$8*$J117))",
    "equation_awqc_org": "=(($C$9/$C117)*$C$3*1000)/($C$8*$J117)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
156605:{
    "order_by": "105",
    "chemical_nm": "1,2-Trans-Dichloroethylene",
    "chemical_label_tx": "1,2-Trans-Dichloroethylene<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "156605",
    "fc_water_org": "100",
    "fc_org": "4,000",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.02",
    "bio_acc_tl2": "3.3",
    "bio_acc_tl3": "4.2",
    "bio_acc_tl4": "4.7",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E31*$D31*$C$3*1000)/($C$4+$C$5*$F31+$C$6*$G31+$C$7*$H31)",
    "equation_awqc_org": "=($E31*$D31*$C$3*1000)/($C$5*$F31+$C$6*$G31+$C$7*$H31)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
193395:{
    "order_by": "61",
    "chemical_nm": "Indeno(1,2,3-cd) Pyrene",
    "chemical_label_tx": "Indeno(1,2,3-cd) Pyrene<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "193395",
    "fc_water_org": "0.0012",
    "fc_org": "0.0013",
    "cancer_slope": "0.73",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "3,900",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C101)*$C$3*1000)/($C$4+($C$8*$J101))",
    "equation_awqc_org": "=(($C$9/$C101)*$C$3*1000)/($C$8*$J101)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
205992:{
    "order_by": "16",
    "chemical_nm": "Benzo(b) Fluoranthene",
    "chemical_label_tx": "Benzo(b) Fluoranthene<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "205992",
    "fc_water_org": "0.0012",
    "fc_org": "0.0013",
    "cancer_slope": "0.73",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "3,900",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C61)*$C$3*1000)/($C$4+($C$8*$J61))",
    "equation_awqc_org": "=(($C$9/$C61)*$C$3*1000)/($C$8*$J61)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
206440:{
    "order_by": "51",
    "chemical_nm": "Fluoranthene",
    "chemical_label_tx": "Fluoranthene",
    "super_script_tx": "",
    "cas_number": "206440",
    "fc_water_org": "20",
    "fc_org": "20",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.04",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "1,500",
    "sig_figs_nu": "1",
    "methodology_type": "BAC",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E91*$D91*$C$3*1000)/($C$4+($C$8*$J91))",
    "equation_awqc_org": "=($D91*$E91*$C$3*1000)/($C$8*$J91)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "(rel_source_cont*ref_dose*BW*1000)/(FCR_T*bio_con)"
},
207089:{
    "order_by": "17",
    "chemical_nm": "Benzo(k) Fluoranthene",
    "chemical_label_tx": "Benzo(k) Fluoranthene<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "207089",
    "fc_water_org": "0.012",
    "fc_org": "0.013",
    "cancer_slope": "0.073",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "3,900",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C62)*$C$3*1000)/($C$4+($C$8*$J62))",
    "equation_awqc_org": "=(($C$9/$C62)*$C$3*1000)/($C$8*$J62)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
218019:{
    "order_by": "37",
    "chemical_nm": "Chrysene",
    "chemical_label_tx": "Chrysene<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "218019",
    "fc_water_org": "0.12",
    "fc_org": "0.13",
    "cancer_slope": "0.0073",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "3,900",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C78)*$C$3*1000)/($C$4+($C$8*$J78))",
    "equation_awqc_org": "=(($C$9/$C78)*$C$3*1000)/($C$8*$J78)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
22967926:{
    "order_by": "65",
    "chemical_nm": "Methylmercury",
    "chemical_label_tx": "Methylmercury<sup>g</sup>",
    "super_script_tx": "g",
    "cas_number": "22967926",
    "fc_water_org": "-",
    "fc_org": "0.3 mg/kg",
    "cancer_slope": "-",
    "rel_source_cont": "0.000027",
    "ref_dose": "0.0001",
    "bio_acc_tl2": "120000",
    "bio_acc_tl3": "680000",
    "bio_acc_tl4": "1200000",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer-custom",
    "equation_awqc_wat_org": "",
    "equation_awqc_org": "=(($E105-$D105)*$C$3)/($C$8)",
    "mapped_equation_awqc_wat_org": "",
    "mapped_equation_awqc_org": "(BW*(ref_dose-rel_source_cont))/(FCR_T)"
},
25550587:{
    "order_by": "46",
    "chemical_nm": "Dinitrophenois",
    "chemical_label_tx": "Dinitrophenois",
    "super_script_tx": "",
    "cas_number": "25550587",
    "fc_water_org": "10",
    "fc_org": "1,000",
    "cancer_slope": "",
    "rel_source_cont": "0.20",
    "ref_dose": "0.002",
    "bio_acc_tl2": "",
    "bio_acc_tl3": "",
    "bio_acc_tl4": "",
    "bio_acc_tot": "",
    "bio_con": "1.51",
    "sig_figs_nu": "1",
    "methodology_type": "BAC",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E86*$D86*$C$3*1000)/($C$4+($C$8*$J86))",
    "equation_awqc_org": "=($D86*$E86*$C$3*1000)/($C$8*$J86)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "(rel_source_cont*ref_dose*BW*1000)/(FCR_T*bio_con)"
},
309002:{
    "order_by": "4",
    "chemical_nm": "Aldrin",
    "chemical_label_tx": "Aldrin<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "309002",
    "fc_water_org": "0.00000077",
    "fc_org": "0.00000077",
    "cancer_slope": "17",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "18000",
    "bio_acc_tl3": "310000",
    "bio_acc_tl4": "650000",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C52)*$C$3*1000/($C$4+$C$5*$F52+$C$6*$G52+$C$7*$H52)",
    "equation_awqc_org": "=(($C$9/$C52)*$C$3*1000)/($C$5*$F52+$C$6*$G52+$C$7*$H52)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
319846:{
    "order_by": "6",
    "chemical_nm": "alpha-BHC",
    "chemical_label_tx": "alpha-BHC",
    "super_script_tx": "",
    "cas_number": "319846",
    "fc_water_org": "0.00036",
    "fc_org": "0.00039",
    "cancer_slope": "6.3",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "1700",
    "bio_acc_tl3": "1400",
    "bio_acc_tl4": "1500",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C53)*$C$3*1000/($C$4+$C$5*$F53+$C$6*$G53+$C$7*$H53)",
    "equation_awqc_org": "=(($C$9/$C53)*$C$3*1000)/($C$5*$F53+$C$6*$G53+$C$7*$H53)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
319857:{
    "order_by": "19",
    "chemical_nm": "beta-BHC (beta-HCH)",
    "chemical_label_tx": "beta-BHC (beta-HCH)<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "319857",
    "fc_water_org": "0.008",
    "fc_org": "0.014",
    "cancer_slope": "1.8",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "110",
    "bio_acc_tl3": "160",
    "bio_acc_tl4": "180",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C63)*$C$3*1000/($C$4+$C$5*$F63+$C$6*$G63+$C$7*$H63)",
    "equation_awqc_org": "=(($C$9/$C63)*$C$3*1000)/($C$5*$F63+$C$6*$G63+$C$7*$H63)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
33213659:{
    "order_by": "20",
    "chemical_nm": "beta-Endosulfan",
    "chemical_label_tx": "beta-Endosulfan",
    "super_script_tx": "",
    "cas_number": "33213659",
    "fc_water_org": "20",
    "fc_org": "40",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.006",
    "bio_acc_tl2": "80",
    "bio_acc_tl3": "110",
    "bio_acc_tl4": "130",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E64*$D64*$C$3*1000)/($C$4+$C$5*$F64+$C$6*$G64+$C$7*$H64)",
    "equation_awqc_org": "=($E64*$D64*$C$3*1000)/($C$5*$F64+$C$6*$G64+$C$7*$H64)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
50293:{
    "order_by": "123",
    "chemical_nm": "4,4'-DDT",
    "chemical_label_tx": "4,4'-DDT<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "50293",
    "fc_water_org": "0.00003",
    "fc_org": "0.00003",
    "cancer_slope": "0.34",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "35000",
    "bio_acc_tl3": "240000",
    "bio_acc_tl4": "1100000",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C48)*$C$3*1000/($C$4+$C$5*$F48+$C$6*$G48+$C$7*$H48)",
    "equation_awqc_org": "=(($C$9/$C48)*$C$3*1000)/($C$5*$F48+$C$6*$G48+$C$7*$H48)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
50328:{
    "order_by": "15",
    "chemical_nm": "Benzo(a) Pyrene",
    "chemical_label_tx": "Benzo(a) Pyrene<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "50328",
    "fc_water_org": "0.00012",
    "fc_org": "0.00013",
    "cancer_slope": "7.3",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "3,900",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C60)*$C$3*1000)/($C$4+($C$8*$J60))",
    "equation_awqc_org": "=(($C$9/$C60)*$C$3*1000)/($C$8*$J60)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
51285:{
    "order_by": "114",
    "chemical_nm": "2,4-Dinitrophenol",
    "chemical_label_tx": "2,4-Dinitrophenol",
    "super_script_tx": "",
    "cas_number": "51285",
    "fc_water_org": "10",
    "fc_org": "300",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.002",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "4.4",
    "sig_figs_nu": "1",
    "methodology_type": "BAC",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E39*$D39*$C$3*1000)/($C$4+($C$8*$J39))",
    "equation_awqc_org": "=($D39*$E39*$C$3*1000)/($C$8*$J39)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "(rel_source_cont*ref_dose*BW*1000)/(FCR_T*bio_con)"
},
534521:{
    "order_by": "118",
    "chemical_nm": "2-Methyl-4,6-Dinitrophenol",
    "chemical_label_tx": "2-Methyl-4,6-Dinitrophenol",
    "super_script_tx": "",
    "cas_number": "534521",
    "fc_water_org": "2",
    "fc_org": "30",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.0003",
    "bio_acc_tl2": "6.8",
    "bio_acc_tl3": "8.9",
    "bio_acc_tl4": "10",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E43*$D43*$C$3*1000)/($C$4+$C$5*$F43+$C$6*$G43+$C$7*$H43)",
    "equation_awqc_org": "=($E43*$D43*$C$3*1000)/($C$5*$F43+$C$6*$G43+$C$7*$H43)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
53703:{
    "order_by": "40",
    "chemical_nm": "Dibenzo(a,h) Anthracene",
    "chemical_label_tx": "Dibenzo(a,h) Anthracene<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "53703",
    "fc_water_org": "0.00012",
    "fc_org": "0.00013",
    "cancer_slope": "7.3",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "3,900",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C80)*$C$3*1000)/($C$4+($C$8*$J80))",
    "equation_awqc_org": "=(($C$9/$C80)*$C$3*1000)/($C$8*$J80)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
541731:{
    "order_by": "106",
    "chemical_nm": "1,3-Dichlorobenzene",
    "chemical_label_tx": "1,3-Dichlorobenzene",
    "super_script_tx": "",
    "cas_number": "541731",
    "fc_water_org": "7",
    "fc_org": "10",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.002",
    "bio_acc_tl2": "31",
    "bio_acc_tl3": "120",
    "bio_acc_tl4": "190",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E32*$D32*$C$3*1000)/($C$4+$C$5*$F32+$C$6*$G32+$C$7*$H32)",
    "equation_awqc_org": "=($E32*$D32*$C$3*1000)/($C$5*$F32+$C$6*$G32+$C$7*$H32)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
542756:{
    "order_by": "107",
    "chemical_nm": "1,3-Dichloropropene",
    "chemical_label_tx": "1,3-Dichloropropene<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "542756",
    "fc_water_org": "0.27",
    "fc_org": "12",
    "cancer_slope": "0.122",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "2.3",
    "bio_acc_tl3": "2.7",
    "bio_acc_tl4": "3.0",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C33)*$C$3*1000/($C$4+$C$5*$F33+$C$6*$G33+$C$7*$H33)",
    "equation_awqc_org": "=(($C$9/$C33)*$C$3*1000)/($C$5*$F33+$C$6*$G33+$C$7*$H33)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
542881:{
    "order_by": "24",
    "chemical_nm": "Bis(Chlormethyl) Ether",
    "chemical_label_tx": "Bis(Chlormethyl) Ether",
    "super_script_tx": "",
    "cas_number": "542881",
    "fc_water_org": "0.00015",
    "fc_org": "0.017",
    "cancer_slope": "220",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "1",
    "bio_acc_tl3": "1",
    "bio_acc_tl4": "1",
    "bio_acc_tot": "",
    "bio_con": "",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C68)*$C$3*1000/($C$4+$C$5*$F68+$C$6*$G68+$C$7*$H68)",
    "equation_awqc_org": "=(($C$9/$C68)*$C$3*1000)/($C$5*$F68+$C$6*$G68+$C$7*$H68)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
56235:{
    "order_by": "28",
    "chemical_nm": "Carbon Tetrachloride",
    "chemical_label_tx": "Carbon Tetrachloride<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "56235",
    "fc_water_org": "0.4",
    "fc_org": "5",
    "cancer_slope": "0.07",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "9.3",
    "bio_acc_tl3": "12",
    "bio_acc_tl4": "14",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C71)*$C$3*1000/($C$4+$C$5*$F71+$C$6*$G71+$C$7*$H71)",
    "equation_awqc_org": "=(($C$9/$C71)*$C$3*1000)/($C$5*$F71+$C$6*$G71+$C$7*$H71)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
56553:{
    "order_by": "14",
    "chemical_nm": "Benzo(a) Anthracene",
    "chemical_label_tx": "Benzo(a) Anthracene<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "56553",
    "fc_water_org": "0.0012",
    "fc_org": "0.0013",
    "cancer_slope": "0.73",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "3,900",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C59)*$C$3*1000)/($C$4+($C$8*$J59))",
    "equation_awqc_org": "=(($C$9/$C59)*$C$3*1000)/($C$8*$J59)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
57125:{
    "order_by": "39",
    "chemical_nm": "Cyanide",
    "chemical_label_tx": "Cyanide<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "57125",
    "fc_water_org": "4",
    "fc_org": "400",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.0006",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "1",
    "sig_figs_nu": "1",
    "methodology_type": "BAC",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E79*$D79*$C$3*1000)/($C$4+($C$8*$J79))",
    "equation_awqc_org": "=($D79*$E79*$C$3*1000)/($C$8*$J79)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "(rel_source_cont*ref_dose*BW*1000)/(FCR_T*bio_con)"
},
57749:{
    "order_by": "29",
    "chemical_nm": "Chlordane",
    "chemical_label_tx": "Chlordane<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "57749",
    "fc_water_org": "0.00031",
    "fc_org": "0.00032",
    "cancer_slope": "0.35",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "5300",
    "bio_acc_tl3": "44000",
    "bio_acc_tl4": "60000",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C72)*$C$3*1000/($C$4+$C$5*$F72+$C$6*$G72+$C$7*$H72)",
    "equation_awqc_org": "=(($C$9/$C72)*$C$3*1000)/($C$5*$F72+$C$6*$G72+$C$7*$H72)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
58899:{
    "order_by": "53",
    "chemical_nm": "Gamma-BHC (HCH); Lindane",
    "chemical_label_tx": "Gamma-BHC (HCH); Lindane<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "58899",
    "fc_water_org": "4.2",
    "fc_org": "4.4",
    "cancer_slope": "-",
    "rel_source_cont": "0.50",
    "ref_dose": "0.0047",
    "bio_acc_tl2": "1200",
    "bio_acc_tl3": "2400",
    "bio_acc_tl4": "2500",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E93*$D93*$C$3*1000)/($C$4+$C$5*$F93+$C$6*$G93+$C$7*$H93)",
    "equation_awqc_org": "=($E93*$D93*$C$3*1000)/($C$5*$F93+$C$6*$G93+$C$7*$H93)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
59507:{
    "order_by": "120",
    "chemical_nm": "3-Methyl-4-Chlorophenol",
    "chemical_label_tx": "3-Methyl-4-Chlorophenol<sup>c</sup>",
    "super_script_tx": "c",
    "cas_number": "59507",
    "fc_water_org": "500",
    "fc_org": "2,000",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.1",
    "bio_acc_tl2": "25",
    "bio_acc_tl3": "34",
    "bio_acc_tl4": "39",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E45*$D45*$C$3*1000)/($C$4+$C$5*$F45+$C$6*$G45+$C$7*$H45)",
    "equation_awqc_org": "=($E45*$D45*$C$3*1000)/($C$5*$F45+$C$6*$G45+$C$7*$H45)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
60571:{
    "order_by": "42",
    "chemical_nm": "Dieldrin",
    "chemical_label_tx": "Dieldrin<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "60571",
    "fc_water_org": "0.0000012",
    "fc_org": "0.0000012",
    "cancer_slope": "16",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "14000",
    "bio_acc_tl3": "210000",
    "bio_acc_tl4": "410000",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C82)*$C$3*1000/($C$4+$C$5*$F82+$C$6*$G82+$C$7*$H82)",
    "equation_awqc_org": "=(($C$9/$C82)*$C$3*1000)/($C$5*$F82+$C$6*$G82+$C$7*$H82)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
608731:{
    "order_by": "58",
    "chemical_nm": "Hexachlorocyclohexane (HCH) - Technical",
    "chemical_label_tx": "Hexachlorocyclohexane (HCH) - Technical",
    "super_script_tx": "",
    "cas_number": "608731",
    "fc_water_org": "0.0066",
    "fc_org": "0.01",
    "cancer_slope": "1.8",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "160",
    "bio_acc_tl3": "220",
    "bio_acc_tl4": "250",
    "bio_acc_tot": "",
    "bio_con": "",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C98)*$C$3*1000/($C$4+$C$5*$F98+$C$6*$G98+$C$7*$H98)",
    "equation_awqc_org": "=(($C$9/$C98)*$C$3*1000)/($C$5*$F98+$C$6*$G98+$C$7*$H98)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
608935:{
    "order_by": "80",
    "chemical_nm": "Pentachlorobenzene",
    "chemical_label_tx": "Pentachlorobenzene",
    "super_script_tx": "",
    "cas_number": "608935",
    "fc_water_org": "0.1",
    "fc_org": "0.1",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.0008",
    "bio_acc_tl2": "3500",
    "bio_acc_tl3": "4500",
    "bio_acc_tl4": "10000",
    "bio_acc_tot": "",
    "bio_con": "",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E114*$D114*$C$3*1000)/($C$4+$C$5*$F114+$C$6*$G114+$C$7*$H114)",
    "equation_awqc_org": "=($E114*$D114*$C$3*1000)/($C$5*$F114+$C$6*$G114+$C$7*$H114)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
621647:{
    "order_by": "77",
    "chemical_nm": "N-Nitrosodi-n-Propylamine",
    "chemical_label_tx": "N-Nitrosodi-n-Propylamine<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "621647",
    "fc_water_org": "0.005",
    "fc_org": "0.51",
    "cancer_slope": "7",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "1.13",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C112)*$C$3*1000)/($C$4+($C$8*$J112))",
    "equation_awqc_org": "=(($C$9/$C112)*$C$3*1000)/($C$8*$J112)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
62759:{
    "order_by": "76",
    "chemical_nm": "N-Nitrosodimethylamine",
    "chemical_label_tx": "N-Nitrosodimethylamine<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "62759",
    "fc_water_org": "0.00069",
    "fc_org": "3",
    "cancer_slope": "51",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "0.026",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C111)*$C$3*1000)/($C$4+($C$8*$J111))",
    "equation_awqc_org": "=(($C$9/$C111)*$C$3*1000)/($C$8*$J111)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
67663:{
    "order_by": "32",
    "chemical_nm": "Chloroform",
    "chemical_label_tx": "Chloroform<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "67663",
    "fc_water_org": "60",
    "fc_org": "2,000",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.01",
    "bio_acc_tl2": "2.8",
    "bio_acc_tl3": "3.4",
    "bio_acc_tl4": "3.8",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E75*$D75*$C$3*1000)/($C$4+$C$5*$F75+$C$6*$G75+$C$7*$H75)",
    "equation_awqc_org": "=($E75*$D75*$C$3*1000)/($C$5*$F75+$C$6*$G75+$C$7*$H75)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
67721:{
    "order_by": "60",
    "chemical_nm": "Hexachloroethane",
    "chemical_label_tx": "Hexachloroethane<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "67721",
    "fc_water_org": "0.1",
    "fc_org": "0.1",
    "cancer_slope": "0.04",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "1200",
    "bio_acc_tl3": "280",
    "bio_acc_tl4": "600",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C100)*$C$3*1000/($C$4+$C$5*$F100+$C$6*$G100+$C$7*$H100)",
    "equation_awqc_org": "=(($C$9/$C100)*$C$3*1000)/($C$5*$F100+$C$6*$G100+$C$7*$H100)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
71432:{
    "order_by": "12",
    "chemical_nm": "Benzene- Upper CSF",
    "chemical_label_tx": "Benzene<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "71432",
    "fc_water_org": "0.58-2.1",
    "fc_org": "16-58",
    "cancer_slope": "0.055",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "3.6",
    "bio_acc_tl3": "4.5",
    "bio_acc_tl4": "5.0",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C57)*$C$3*1000/($C$4+$C$5*$F57+$C$6*$G57+$C$7*$H57)",
    "equation_awqc_org": "=(($C$9/$C57)*$C$3*1000)/($C$5*$F57+$C$6*$G57+$C$7*$H57)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
71556:{
    "order_by": "95",
    "chemical_nm": "1,1,1-Trichloroethane",
    "chemical_label_tx": "1,1,1-Trichloroethane<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "71556",
    "fc_water_org": "10,000",
    "fc_org": "200,000",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "2",
    "bio_acc_tl2": "6.9",
    "bio_acc_tl3": "9",
    "bio_acc_tl4": "10",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E21*$D21*$C$3*1000)/($C$4+$C$5*$F21+$C$6*$G21+$C$7*$H21)",
    "equation_awqc_org": "=($E21*$D21*$C$3*1000)/($C$5*$F21+$C$6*$G21+$C$7*$H21)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
72208:{
    "order_by": "49",
    "chemical_nm": "Endrin",
    "chemical_label_tx": "Endrin",
    "super_script_tx": "",
    "cas_number": "72208",
    "fc_water_org": "0.03",
    "fc_org": "0.03",
    "cancer_slope": "-",
    "rel_source_cont": "0.80",
    "ref_dose": "0.0003",
    "bio_acc_tl2": "4600",
    "bio_acc_tl3": "36000",
    "bio_acc_tl4": "46000",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E88*$D88*$C$3*1000)/($C$4+$C$5*$F88+$C$6*$G88+$C$7*$H88)",
    "equation_awqc_org": "=($E88*$D88*$C$3*1000)/($C$5*$F88+$C$6*$G88+$C$7*$H88)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
72435:{
    "order_by": "66",
    "chemical_nm": "Methoxychlor",
    "chemical_label_tx": "Methoxychlor<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "72435",
    "fc_water_org": "0.02",
    "fc_org": "0.02",
    "cancer_slope": "-",
    "rel_source_cont": "0.80",
    "ref_dose": "0.00002",
    "bio_acc_tl2": "1400",
    "bio_acc_tl3": "4800",
    "bio_acc_tl4": "4400",
    "bio_acc_tot": "",
    "bio_con": "",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E106*$D106*$C$3*1000)/($C$4+$C$5*$F106+$C$6*$G106+$C$7*$H106)",
    "equation_awqc_org": "=($E106*$D106*$C$3*1000)/($C$5*$F106+$C$6*$G106+$C$7*$H106)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
72548:{
    "order_by": "121",
    "chemical_nm": "4,4'-DDD",
    "chemical_label_tx": "4,4'-DDD<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "72548",
    "fc_water_org": "0.00012",
    "fc_org": "0.00012",
    "cancer_slope": "0.24",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "33000",
    "bio_acc_tl3": "140000",
    "bio_acc_tl4": "240000",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C46)*$C$3*1000/($C$4+$C$5*$F46+$C$6*$G46+$C$7*$H46)",
    "equation_awqc_org": "=(($C$9/$C46)*$C$3*1000)/($C$5*$F46+$C$6*$G46+$C$7*$H46)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
72559:{
    "order_by": "122",
    "chemical_nm": "4,4'-DDE",
    "chemical_label_tx": "4,4'-DDE<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "72559",
    "fc_water_org": "0.000018",
    "fc_org": "0.000018",
    "cancer_slope": "0.167",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "270000",
    "bio_acc_tl3": "1100000",
    "bio_acc_tl4": "3100000",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C47)*$C$3*1000/($C$4+$C$5*$F47+$C$6*$G47+$C$7*$H47)",
    "equation_awqc_org": "=(($C$9/$C47)*$C$3*1000)/($C$5*$F47+$C$6*$G47+$C$7*$H47)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
7421934:{
    "order_by": "48",
    "chemical_nm": "Endrin Aldehyde",
    "chemical_label_tx": "Endrin Aldehyde<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "7421934",
    "fc_water_org": "1",
    "fc_org": "1",
    "cancer_slope": "-",
    "rel_source_cont": "0.80",
    "ref_dose": "0.0003",
    "bio_acc_tl2": "440",
    "bio_acc_tl3": "920",
    "bio_acc_tl4": "850",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E89*$D89*$C$3*1000)/($C$4+$C$5*$F89+$C$6*$G89+$C$7*$H89)",
    "equation_awqc_org": "=($E89*$D89*$C$3*1000)/($C$5*$F89+$C$6*$G89+$C$7*$H89)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
7440020:{
    "order_by": "69",
    "chemical_nm": "Nickel",
    "chemical_label_tx": "Nickel<sup>d</sup>",
    "super_script_tx": "d",
    "cas_number": "7440020",
    "fc_water_org": "610",
    "fc_org": "4,600",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.02",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "47",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E107*$D107*$C$3*1000)/($C$4+($C$8*$J107))",
    "equation_awqc_org": "=($D107*$E107*$C$3*1000)/($C$8*$J107)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "(rel_source_cont*ref_dose*BW*1000)/(FCR_T*bio_con)"
},
7440360:{
    "order_by": "8",
    "chemical_nm": "Antimony",
    "chemical_label_tx": "Antimony<sup>a,d</sup>",
    "super_script_tx": "a,d",
    "cas_number": "7440360",
    "fc_water_org": "5.6",
    "fc_org": "640",
    "cancer_slope": "-",
    "rel_source_cont": "0.40",
    "ref_dose": "0.0004",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "1",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E56*$D56*$C$3*1000)/($C$4+($C$8*$J56))",
    "equation_awqc_org": "=($D56*$E56*$C$3*1000)/($C$8*$J56)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "(rel_source_cont*ref_dose*BW*1000)/(FCR_T*bio_con)"
},
7440666:{
    "order_by": "94",
    "chemical_nm": "Zinc",
    "chemical_label_tx": "Zinc<sup>c</sup>",
    "super_script_tx": "c",
    "cas_number": "7440666",
    "fc_water_org": "7,400",
    "fc_org": "26,000",
    "cancer_slope": "-",
    "rel_source_cont": "1",
    "ref_dose": "0.3",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "47",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E125*$D125*$C$3*1000)/($C$4+($C$8*$J125))",
    "equation_awqc_org": "=($D125*$E125*$C$3*1000)/($C$8*$J125)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "(rel_source_cont*ref_dose*BW*1000)/(FCR_T*bio_con)"
},
74839:{
    "order_by": "67",
    "chemical_nm": "Methyl Bromide",
    "chemical_label_tx": "Methyl Bromide",
    "super_script_tx": "",
    "cas_number": "74839",
    "fc_water_org": "100",
    "fc_org": "10,000",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.02",
    "bio_acc_tl2": "1.2",
    "bio_acc_tl3": "1.3",
    "bio_acc_tl4": "1.4",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E103*$D103*$C$3*1000)/($C$4+$C$5*$F103+$C$6*$G103+$C$7*$H103)",
    "equation_awqc_org": "=($E103*$D103*$C$3*1000)/($C$5*$F103+$C$6*$G103+$C$7*$H103)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
75014:{
    "order_by": "93",
    "chemical_nm": "Vinyl Chloride",
    "chemical_label_tx": "Vinyl Chloride<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "75014",
    "fc_water_org": "0.022",
    "fc_org": "1.6",
    "cancer_slope": "1.5",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "1.4",
    "bio_acc_tl3": "1.6",
    "bio_acc_tl4": "1.7",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C124)*$C$3*1000/($C$4+$C$5*$F124+$C$6*$G124+$C$7*$H124)",
    "equation_awqc_org": "=(($C$9/$C124)*$C$3*1000)/($C$5*$F124+$C$6*$G124+$C$7*$H124)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
75092:{
    "order_by": "68",
    "chemical_nm": "Methylene Chloride",
    "chemical_label_tx": "Methylene Chloride<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "75092",
    "fc_water_org": "20",
    "fc_org": "1,000",
    "cancer_slope": "0.002",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "1.4",
    "bio_acc_tl3": "1.5",
    "bio_acc_tl4": "1.6",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C104)*$C$3*1000/($C$4+$C$5*$F104+$C$6*$G104+$C$7*$H104)",
    "equation_awqc_org": "=(($C$9/$C104)*$C$3*1000)/($C$5*$F104+$C$6*$G104+$C$7*$H104)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
75252:{
    "order_by": "25",
    "chemical_nm": "Bromoform",
    "chemical_label_tx": "Bromoform<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "75252",
    "fc_water_org": "7",
    "fc_org": "120",
    "cancer_slope": "0.0045",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "5.8",
    "bio_acc_tl3": "7.5",
    "bio_acc_tl4": "8.5",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C69)*$C$3*1000/($C$4+$C$5*$F69+$C$6*$G69+$C$7*$H69)",
    "equation_awqc_org": "=(($C$9/$C69)*$C$3*1000)/($C$5*$F69+$C$6*$G69+$C$7*$H69)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
75274:{
    "order_by": "41",
    "chemical_nm": "Dichlorobromomethane",
    "chemical_label_tx": "Dichlorobromomethane<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "75274",
    "fc_water_org": "0.95",
    "fc_org": "27",
    "cancer_slope": "0.034",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "3.4",
    "bio_acc_tl3": "4.3",
    "bio_acc_tl4": "4.8",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C81)*$C$3*1000/($C$4+$C$5*$F81+$C$6*$G81+$C$7*$H81)",
    "equation_awqc_org": "=(($C$9/$C81)*$C$3*1000)/($C$5*$F81+$C$6*$G81+$C$7*$H81)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
75354:{
    "order_by": "98",
    "chemical_nm": "1,1-Dichloroethylene",
    "chemical_label_tx": "1,1-Dichloroethylene<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "75354",
    "fc_water_org": "300",
    "fc_org": "20,000",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.05",
    "bio_acc_tl2": "2",
    "bio_acc_tl3": "2.4",
    "bio_acc_tl4": "2.6",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E24*$D24*$C$3*1000)/($C$4+$C$5*$F24+$C$6*$G24+$C$7*$H24)",
    "equation_awqc_org": "=($E24*$D24*$C$3*1000)/($C$5*$F24+$C$6*$G24+$C$7*$H24)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
76448:{
    "order_by": "55",
    "chemical_nm": "Heptachlor",
    "chemical_label_tx": "Heptachlor<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "76448",
    "fc_water_org": "0.0000059",
    "fc_org": "0.0000059",
    "cancer_slope": "4.1",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "12000",
    "bio_acc_tl3": "180000",
    "bio_acc_tl4": "330000",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C94)*$C$3*1000/($C$4+$C$5*$F94+$C$6*$G94+$C$7*$H94)",
    "equation_awqc_org": "=(($C$9/$C94)*$C$3*1000)/($C$5*$F94+$C$6*$G94+$C$7*$H94)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
77474:{
    "order_by": "59",
    "chemical_nm": "Hexachlorocyclopentadiene",
    "chemical_label_tx": "Hexachlorocyclopentadiene<sup>a,c</sup>",
    "super_script_tx": "a,c",
    "cas_number": "77474",
    "fc_water_org": "4",
    "fc_org": "4",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.006",
    "bio_acc_tl2": "620",
    "bio_acc_tl3": "1500",
    "bio_acc_tl4": "1300",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E99*$D99*$C$3*1000)/($C$4+$C$5*$F99+$C$6*$G99+$C$7*$H99)",
    "equation_awqc_org": "=($E99*$D99*$C$3*1000)/($C$5*$F99+$C$6*$G99+$C$7*$H99)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
7782492:{
    "order_by": "86",
    "chemical_nm": "Selenium",
    "chemical_label_tx": "Selenium<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "7782492",
    "fc_water_org": "170",
    "fc_org": "4,200",
    "cancer_slope": "-",
    "rel_source_cont": "1",
    "ref_dose": "0.005",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "4.8",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E119*$D119*$C$3*1000)/($C$4+($C$8*$J119))",
    "equation_awqc_org": "=($D119*$E119*$C$3*1000)/($C$8*$J119)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "(rel_source_cont*ref_dose*BW*1000)/(FCR_T*bio_con)"
},
78591:{
    "order_by": "62",
    "chemical_nm": "Isophorone",
    "chemical_label_tx": "Isophorone<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "78591",
    "fc_water_org": "34",
    "fc_org": "1,800",
    "cancer_slope": "0.00095",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "1.9",
    "bio_acc_tl3": "2.2",
    "bio_acc_tl4": "2.4",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C102)*$C$3*1000/($C$4+$C$5*$F102+$C$6*$G102+$C$7*$H102)",
    "equation_awqc_org": "=(($C$9/$C102)*$C$3*1000)/($C$5*$F102+$C$6*$G102+$C$7*$H102)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
78875:{
    "order_by": "103",
    "chemical_nm": "1,2-Dichloropropane",
    "chemical_label_tx": "1,2-Dichloropropane<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "78875",
    "fc_water_org": "0.9",
    "fc_org": "31",
    "cancer_slope": "0.036",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "2.9",
    "bio_acc_tl3": "3.5",
    "bio_acc_tl4": "3.9",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C29)*$C$3*1000/($C$4+$C$5*$F29+$C$6*$G29+$C$7*$H29)",
    "equation_awqc_org": "=(($C$9/$C29)*$C$3*1000)/($C$5*$F29+$C$6*$G29+$C$7*$H29)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
79005:{
    "order_by": "97",
    "chemical_nm": "1,1,2-Trichloroethane",
    "chemical_label_tx": "1,1,2-Trichloroethane<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "79005",
    "fc_water_org": "0.55",
    "fc_org": "8.9",
    "cancer_slope": "0.057",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "6",
    "bio_acc_tl3": "7.8",
    "bio_acc_tl4": "8.9",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C23)*$C$3*1000/($C$4+$C$5*$F23+$C$6*$G23+$C$7*$H23)",
    "equation_awqc_org": "=(($C$9/$C23)*$C$3*1000)/($C$5*$F23+$C$6*$G23+$C$7*$H23)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
79016:{
    "order_by": "92",
    "chemical_nm": "Trichloroethylene",
    "chemical_label_tx": "Trichloroethylene<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "79016",
    "fc_water_org": "0.6",
    "fc_org": "7",
    "cancer_slope": "0.05",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "8.7",
    "bio_acc_tl3": "12",
    "bio_acc_tl4": "13",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C123)*$C$3*1000/($C$4+$C$5*$F123+$C$6*$G123+$C$7*$H123)",
    "equation_awqc_org": "=(($C$9/$C123)*$C$3*1000)/($C$5*$F123+$C$6*$G123+$C$7*$H123)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
79345:{
    "order_by": "96",
    "chemical_nm": "1,1,2,2-Tetrachloroethane",
    "chemical_label_tx": "1,1,2,2-Tetrachloroethane<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "79345",
    "fc_water_org": "0.2",
    "fc_org": "3",
    "cancer_slope": "0.2",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "5.7",
    "bio_acc_tl3": "7.4",
    "bio_acc_tl4": "8.4",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C22)*$C$3*1000/($C$4+$C$5*$F22+$C$6*$G22+$C$7*$H22)",
    "equation_awqc_org": "=(($C$9/$C22)*$C$3*1000)/($C$5*$F22+$C$6*$G22+$C$7*$H22)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
8001352:{
    "order_by": "91",
    "chemical_nm": "Toxaphene",
    "chemical_label_tx": "Toxaphene<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "8001352",
    "fc_water_org": "0.0007",
    "fc_org": "0.00071",
    "cancer_slope": "1.1",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "1,700",
    "bio_acc_tl3": "6,600",
    "bio_acc_tl4": "6,300",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C122)*$C$3*1000/($C$4+$C$5*$F122+$C$6*$G122+$C$7*$H122)",
    "equation_awqc_org": "=(($C$9/$C122)*$C$3*1000)/($C$5*$F122+$C$6*$G122+$C$7*$H122)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
83329:{
    "order_by": "1",
    "chemical_nm": "Acenaphthene",
    "chemical_label_tx": "Acenaphthene<sup>c</sup>",
    "super_script_tx": "c",
    "cas_number": "83329",
    "fc_water_org": "70",
    "fc_org": "90",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.06",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "510",
    "sig_figs_nu": "1",
    "methodology_type": "BAC",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E49*$D49*$C$3*1000)/($C$4+($C$8*$J49))",
    "equation_awqc_org": "=($D49*$E49*$C$3*1000)/($C$8*$J49)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "(rel_source_cont*ref_dose*BW*1000)/(FCR_T*bio_con)"
},
84662:{
    "order_by": "43",
    "chemical_nm": "Diethyl Phthalate",
    "chemical_label_tx": "Diethyl Phthalate",
    "super_script_tx": "",
    "cas_number": "84662",
    "fc_water_org": "600",
    "fc_org": "600",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.8",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "920",
    "sig_figs_nu": "1",
    "methodology_type": "BAC",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E83*$D83*$C$3*1000)/($C$4+($C$8*$J83))",
    "equation_awqc_org": "=($D83*$E83*$C$3*1000)/($C$8*$J83)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "(rel_source_cont*ref_dose*BW*1000)/(FCR_T*bio_con)"
},
84742:{
    "order_by": "45",
    "chemical_nm": "Di-n-Butyl Phthalate",
    "chemical_label_tx": "Di-n-Butyl Phthalate",
    "super_script_tx": "",
    "cas_number": "84742",
    "fc_water_org": "20",
    "fc_org": "30",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.1",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "2,900",
    "sig_figs_nu": "1",
    "methodology_type": "BAC",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E85*$D85*$C$3*1000)/($C$4+($C$8*$J85))",
    "equation_awqc_org": "=($D85*$E85*$C$3*1000)/($C$8*$J85)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "(rel_source_cont*ref_dose*BW*1000)/(FCR_T*bio_con)"
},
85687:{
    "order_by": "26",
    "chemical_nm": "Butylbenzyl Phthalate",
    "chemical_label_tx": "Butylbenzyl Phthalate",
    "super_script_tx": "",
    "cas_number": "85687",
    "fc_water_org": "0.1",
    "fc_org": "0.1",
    "cancer_slope": "0.0019",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "19,000",
    "sig_figs_nu": "1",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C70)*$C$3*1000)/($C$4+($C$8*$J70))",
    "equation_awqc_org": "=(($C$9/$C70)*$C$3*1000)/($C$8*$J70)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
86306:{
    "order_by": "78",
    "chemical_nm": "N-Nitrosodiphenylamine",
    "chemical_label_tx": "N-Nitrosodiphenylamine<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "86306",
    "fc_water_org": "3.3",
    "fc_org": "6",
    "cancer_slope": "0.0049",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "",
    "bio_con": "136",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C113)*$C$3*1000)/($C$4+($C$8*$J113))",
    "equation_awqc_org": "=(($C$9/$C113)*$C$3*1000)/($C$8*$J113)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
86737:{
    "order_by": "52",
    "chemical_nm": "Fluorene",
    "chemical_label_tx": "Fluorene",
    "super_script_tx": "",
    "cas_number": "86737",
    "fc_water_org": "50",
    "fc_org": "70",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.04",
    "bio_acc_tl2": "230",
    "bio_acc_tl3": "450",
    "bio_acc_tl4": "710",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E92*$D92*$C$3*1000)/($C$4+$C$5*$F92+$C$6*$G92+$C$7*$H92)",
    "equation_awqc_org": "=($E92*$D92*$C$3*1000)/($C$5*$F92+$C$6*$G92+$C$7*$H92)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
87683:{
    "order_by": "57",
    "chemical_nm": "Hexachlorobutadiene",
    "chemical_label_tx": "Hexachlorobutadiene<sup>a,b</sup>",
    "super_script_tx": "a,b",
    "cas_number": "87683",
    "fc_water_org": "0.01",
    "fc_org": "0.01",
    "cancer_slope": "0.04",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "23000",
    "bio_acc_tl3": "2800",
    "bio_acc_tl4": "1100",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C97)*$C$3*1000/($C$4+$C$5*$F97+$C$6*$G97+$C$7*$H97)",
    "equation_awqc_org": "=(($C$9/$C97)*$C$3*1000)/($C$5*$F97+$C$6*$G97+$C$7*$H97)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
87865:{
    "order_by": "81",
    "chemical_nm": "Pentachlorophenol (PCP)",
    "chemical_label_tx": "Pentachlorophenol (PCP)<sup>a,b,c</sup>",
    "super_script_tx": "a,b,c",
    "cas_number": "87865",
    "fc_water_org": "0.03",
    "fc_org": "0.04",
    "cancer_slope": "0.4",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "44",
    "bio_acc_tl3": "290",
    "bio_acc_tl4": "520",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C115)*$C$3*1000/($C$4+$C$5*$F115+$C$6*$G115+$C$7*$H115)",
    "equation_awqc_org": "=(($C$9/$C115)*$C$3*1000)/($C$5*$F115+$C$6*$G115+$C$7*$H115)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
88062:{
    "order_by": "111",
    "chemical_nm": "2,4,6-Trichlorophenol",
    "chemical_label_tx": "2,4,6-Trichlorophenol<sup>b,c</sup>",
    "super_script_tx": "b,c",
    "cas_number": "88062",
    "fc_water_org": "1.5",
    "fc_org": "2.8",
    "cancer_slope": "0.011",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "94",
    "bio_acc_tl3": "130",
    "bio_acc_tl4": "150",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C36)*$C$3*1000/($C$4+$C$5*$F36+$C$6*$G36+$C$7*$H36)",
    "equation_awqc_org": "=(($C$9/$C36)*$C$3*1000)/($C$5*$F36+$C$6*$G36+$C$7*$H36)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
91587:{
    "order_by": "116",
    "chemical_nm": "2-Chloronaphthalene",
    "chemical_label_tx": "2-Chloronaphthalene",
    "super_script_tx": "",
    "cas_number": "91587",
    "fc_water_org": "800",
    "fc_org": "1,000",
    "cancer_slope": "-",
    "rel_source_cont": "0.80",
    "ref_dose": "0.08",
    "bio_acc_tl2": "150",
    "bio_acc_tl3": "210",
    "bio_acc_tl4": "240",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E41*$D41*$C$3*1000)/($C$4+$C$5*$F41+$C$6*$G41+$C$7*$H41)",
    "equation_awqc_org": "=($E41*$D41*$C$3*1000)/($C$5*$F41+$C$6*$G41+$C$7*$H41)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
91941:{
    "order_by": "119",
    "chemical_nm": "3,3'-Dichlorobenzidine",
    "chemical_label_tx": "3,3'-Dichlorobenzidine<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "91941",
    "fc_water_org": "0.049",
    "fc_org": "0.15",
    "cancer_slope": "0.45",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "44",
    "bio_acc_tl3": "60",
    "bio_acc_tl4": "69",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C44)*$C$3*1000/($C$4+$C$5*$F44+$C$6*$G44+$C$7*$H44)",
    "equation_awqc_org": "=(($C$9/$C44)*$C$3*1000)/($C$5*$F44+$C$6*$G44+$C$7*$H44)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
924163:{
    "order_by": "73",
    "chemical_nm": "Nitrosodibutylamine",
    "chemical_label_tx": "Nitrosodibutylamine<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "924163",
    "fc_water_org": "0.0063",
    "fc_org": "0.22",
    "cancer_slope": "5.43",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "-",
    "bio_con": "3.38",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C109)*$C$3*1000)/($C$4+($C$8*$J109))",
    "equation_awqc_org": "=(($C$9/$C109)*$C$3*1000)/($C$8*$J109)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
92875:{
    "order_by": "13",
    "chemical_nm": "Benzidine",
    "chemical_label_tx": "Benzidine<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "92875",
    "fc_water_org": "0.00014",
    "fc_org": "0.011",
    "cancer_slope": "230",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "1.4",
    "bio_acc_tl3": "1.6",
    "bio_acc_tl4": "1.7",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=($C$9/$C58)*$C$3*1000/($C$4+$C$5*$F58+$C$6*$G58+$C$7*$H58)",
    "equation_awqc_org": "=(($C$9/$C58)*$C$3*1000)/($C$5*$F58+$C$6*$G58+$C$7*$H58)",
    "mapped_equation_awqc_wat_org": "(ELCR/cancer_slope)*BW*1000/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
930552:{
    "order_by": "75",
    "chemical_nm": "Nitrosopyrrolidine",
    "chemical_label_tx": "Nitrosopyrrolidine<sup>b</sup>",
    "super_script_tx": "b",
    "cas_number": "930552",
    "fc_water_org": "0.016",
    "fc_org": "34",
    "cancer_slope": "2.13",
    "rel_source_cont": "-",
    "ref_dose": "-",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "-",
    "bio_con": "0.055",
    "sig_figs_nu": "2",
    "methodology_type": "BAC",
    "cancer_bol": "cancer",
    "equation_awqc_wat_org": "=(($C$9/$C110)*$C$3*1000)/($C$4+($C$8*$J110))",
    "equation_awqc_org": "=(($C$9/$C110)*$C$3*1000)/($C$8*$J110)",
    "mapped_equation_awqc_wat_org": "((ELCR/cancer_slope)*BW*1000)/(DW+(FCR_T*bio_con))",
    "mapped_equation_awqc_org": "((ELCR/cancer_slope)*BW*1000)/(FCR_T*bio_con)"
},
93721:{
    "order_by": "34",
    "chemical_nm": "Chlorophenoxy Herbicide (2,4,5-TP) [Silvex]",
    "chemical_label_tx": "Chlorophenoxy Herbicide (2,4,5-TP) [Silvex]<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "93721",
    "fc_water_org": "100",
    "fc_org": "400",
    "cancer_slope": "-",
    "rel_source_cont": "0.80",
    "ref_dose": "0.008",
    "bio_acc_tl2": "",
    "bio_acc_tl3": "",
    "bio_acc_tl4": "",
    "bio_acc_tot": "58",
    "bio_con": "",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer-custom",
    "equation_awqc_wat_org": "=($E77*$D77*$C$3*1000)/($C$4+($I77*$C$8))",
    "equation_awqc_org": "=$E77*$D77*$C$3*1000/($I77*$C$8)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(bio_acc_tot*FCR_T))",
    "mapped_equation_awqc_org": "ref_dose*rel_source_cont*BW*1000/(bio_acc_tot*FCR_T)"
},
94757:{
    "order_by": "33",
    "chemical_nm": "Chlorophenoxy Herbicide (2,4-D)",
    "chemical_label_tx": "Chlorophenoxy Herbicide (2,4-D)<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "94757",
    "fc_water_org": "1,300",
    "fc_org": "12,000",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.21",
    "bio_acc_tl2": "-",
    "bio_acc_tl3": "-",
    "bio_acc_tl4": "-",
    "bio_acc_tot": "13",
    "bio_con": "",
    "sig_figs_nu": "2",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer-custom",
    "equation_awqc_wat_org": "=($E76*$D76*$C$3*1000)/($C$4+($I76*$C$8))",
    "equation_awqc_org": "=$E76*$D76*$C$3*1000/($I76*$C$8)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+(bio_acc_tot*FCR_T))",
    "mapped_equation_awqc_org": "ref_dose*rel_source_cont*BW*1000/(bio_acc_tot*FCR_T)"
},
95501:{
    "order_by": "101",
    "chemical_nm": "1,2-Dichlorobenzene",
    "chemical_label_tx": "1,2-Dichlorobenzene<sup>a</sup>",
    "super_script_tx": "a",
    "cas_number": "95501",
    "fc_water_org": "1,000",
    "fc_org": "3,000",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.3",
    "bio_acc_tl2": "52",
    "bio_acc_tl3": "71",
    "bio_acc_tl4": "82",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E27*$D27*$C$3*1000)/($C$4+$C$5*$F27+$C$6*$G27+$C$7*$H27)",
    "equation_awqc_org": "=($E27*$D27*$C$3*1000)/($C$5*$F27+$C$6*$G27+$C$7*$H27)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
95578:{
    "order_by": "117",
    "chemical_nm": "2-Chlorophenol",
    "chemical_label_tx": "2-Chlorophenol<sup>c</sup>",
    "super_script_tx": "c",
    "cas_number": "95578",
    "fc_water_org": "30",
    "fc_org": "800",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.005",
    "bio_acc_tl2": "3.8",
    "bio_acc_tl3": "4.8",
    "bio_acc_tl4": "5.4",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E42*$D42*$C$3*1000)/($C$4+$C$5*$F42+$C$6*$G42+$C$7*$H42)",
    "equation_awqc_org": "=($E42*$D42*$C$3*1000)/($C$5*$F42+$C$6*$G42+$C$7*$H42)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
95943:{
    "order_by": "99",
    "chemical_nm": "1,2,4,5-Tetrachlorobenzene",
    "chemical_label_tx": "1,2,4,5-Tetrachlorobenzene",
    "super_script_tx": "",
    "cas_number": "95943",
    "fc_water_org": "0.03",
    "fc_org": "0.03",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.0003",
    "bio_acc_tl2": "17000",
    "bio_acc_tl3": "2900",
    "bio_acc_tl4": "1500",
    "bio_acc_tot": "",
    "bio_con": "",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E26*$D26*$C$3*1000)/($C$4+$C$5*$F26+$C$6*$G26+$C$7*$H26)",
    "equation_awqc_org": "=($E26*$D26*$C$3*1000)/($C$5*$F26+$C$6*$G26+$C$7*$H26)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
95954:{
    "order_by": "110",
    "chemical_nm": "2,4,5-Trichlorophenol",
    "chemical_label_tx": "2,4,5-Trichlorophenol<sup>c</sup>",
    "super_script_tx": "c",
    "cas_number": "95954",
    "fc_water_org": "300",
    "fc_org": "600",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.1",
    "bio_acc_tl2": "100",
    "bio_acc_tl3": "140",
    "bio_acc_tl4": "160",
    "bio_acc_tot": "",
    "bio_con": "",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E35*$D35*$C$3*1000)/($C$4+$C$5*$F35+$C$6*$G35+$C$7*$H35)",
    "equation_awqc_org": "=($E35*$D35*$C$3*1000)/($C$5*$F35+$C$6*$G35+$C$7*$H35)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
959988:{
    "order_by": "5",
    "chemical_nm": "alpha-Endosulfan",
    "chemical_label_tx": "alpha-Endosulfan",
    "super_script_tx": "",
    "cas_number": "959988",
    "fc_water_org": "20",
    "fc_org": "30",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.006",
    "bio_acc_tl2": "130",
    "bio_acc_tl3": "180",
    "bio_acc_tl4": "200",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E54*$D54*$C$3*1000)/($C$4+$C$5*$F54+$C$6*$G54+$C$7*$H54)",
    "equation_awqc_org": "=($E54*$D54*$C$3*1000)/($C$5*$F54+$C$6*$G54+$C$7*$H54)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
},
98953:{
    "order_by": "71",
    "chemical_nm": "Nitrobenzene",
    "chemical_label_tx": "Nitrobenzene<sup>c</sup>",
    "super_script_tx": "c",
    "cas_number": "98953",
    "fc_water_org": "10",
    "fc_org": "600",
    "cancer_slope": "-",
    "rel_source_cont": "0.20",
    "ref_dose": "0.002",
    "bio_acc_tl2": "2.3",
    "bio_acc_tl3": "2.8",
    "bio_acc_tl4": "3.1",
    "bio_acc_tot": "",
    "bio_con": "-",
    "sig_figs_nu": "1",
    "methodology_type": "BAF",
    "cancer_bol": "non-cancer",
    "equation_awqc_wat_org": "=($E108*$D108*$C$3*1000)/($C$4+$C$5*$F108+$C$6*$G108+$C$7*$H108)",
    "equation_awqc_org": "=($E108*$D108*$C$3*1000)/($C$5*$F108+$C$6*$G108+$C$7*$H108)",
    "mapped_equation_awqc_wat_org": "(ref_dose*rel_source_cont*BW*1000)/(DW+FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)",
    "mapped_equation_awqc_org": "(ref_dose*rel_source_cont*BW*1000)/(FCR_2*bio_acc_tl2+FCR_3*bio_acc_tl3+FCR_4*bio_acc_tl4)"
}}
};